# 03_Numpy_1_array

## 배열 생성 코드

#### 리스트 형식의 2차 배열 tmp 형식지정자 그대로 배열 출력

In [1]:
import numpy as np

tmp = [[1,4,5,8],[21,23,15,11]] # 리스트 형식의 2차 배열 tmp
np.array(tmp)

array([[ 1,  4,  5,  8],
       [21, 23, 15, 11]])

In [2]:
print(type(tmp))
print(type(tmp[1][3]))

<class 'list'>
<class 'int'>


#### tmp를 float로 바꾼 fl_tmp 배열 출력

In [3]:
fl_tmp = np.array(tmp, float) # float로 변한하여 배열 출력
fl_tmp

array([[ 1.,  4.,  5.,  8.],
       [21., 23., 15., 11.]])

In [4]:
print(type(fl_tmp))
print(type(fl_tmp[1][3]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


## 넘파이 배열 데이터 구조

In [5]:
test_array = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(test_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
print(test_array.dtype)
print(test_array.ndim)
print(test_array.shape)
print(test_array.strides)

int64
2
(3, 3)
(24, 8)


## 벡터 (1차원 배열)

In [7]:
vector = np.array([1, 4, 5, "8"], float) # 형식 섞여도 괜찮다!
vector

array([1., 4., 5., 8.])

In [8]:
print(vector.dtype)
print(vector.ndim)
print(vector.shape)
print(vector.strides)

float64
1
(4,)
(8,)


## 매트릭스 (2차원 배열)

In [9]:
matrix = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8]])
matrix

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [10]:
print(matrix.dtype)
print(matrix.ndim)
print(matrix.shape)
print(matrix.strides)

int64
2
(3, 4)
(32, 8)


In [11]:
print(type(matrix[1][3]))

<class 'numpy.int64'>


## 텐서 (3차원 배열)

In [12]:
tensor_rank3 = [
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
]

tensor_rank3

[[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
 [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
 [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]

In [13]:
tensor_rank3 = np.array(tensor_rank3, int)
tensor_rank3

array([[[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]]])

In [14]:
print(tensor_rank3.dtype)
print(tensor_rank3.ndim)
print(tensor_rank3.shape)
print(tensor_rank3.strides)

int64
3
(3, 3, 4)
(96, 32, 8)


## 이 외 정보

#### 원소 개수 (변수.size)

In [15]:
print(vector.size)
print(matrix.size)
print(tensor_rank3.size)

4
12
36


#### 원소의 크기(byte) (변수.itemsize)

In [16]:
print(vector.itemsize)
print(matrix.itemsize)
print(tensor_rank3.itemsize)

8
8
8
