<a href="https://colab.research.google.com/github/ddah0329/Study-MachineLearning/blob/main/KBU_2024_ML/03_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

test_list = [[1,4,5,8],[1,4,5,122]] #파이썬 기본 배열
npArr = np.array(test_list)
print(npArr)

[[  1   4   5   8]
 [  1   4   5 122]]


In [ ]:
print(type(test_list))
print(type(test_list[1][3]))

print(type(npArr[0]))
print(type(npArr[1][3]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
test_array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(test_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(test_array.dtype)

# 몇차원이다
print(test_array.ndim)

# 모양 : 데이터 구조 : 3개의 그룹으로 되어있는데 각 그룹에 3개의 데이터가 있다.
print(test_array.shape)

# 그룹의 크기
print(test_array.strides)

int64
2
(3, 3)
(24, 8)


In [ ]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
x.reshape(-1,) # 호출만 한 것 이므로 완전히 변한 것이 아님

array([1, 2, 5, 8, 1, 2, 5, 8])

In [ ]:
x = x.reshape(-1,) # 이렇게 할당 해줘야 완전히 바뀌게 됨
x

array([1, 2, 5, 8, 1, 2, 5, 8])

In [ ]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])