# 03_Numpy_step

### 형태 [시작인덱스 : 마지막 인덱스 : 증가값]

In [1]:
import numpy as np

step_ex = np.array(range(15), int).reshape(3,-1)
step_ex

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
step_ex[:, ::2] # 모든 행인데 oxoxo으로 진행

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [3]:
step_ex[::2, ::3] # 0,2행인데 oxxox으로 진행

array([[ 0,  3],
       [10, 13]])