# 03_Numpy_onesZerosEmpty

### ones() : 1로만 구성된 넘파이 배열

In [1]:
import numpy as np

np.ones(shape=(5,2), dtype = np.int8) # 5개 가로 행에 2개의 세로 줄

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

### zeros() : 0으로만 구성된 넘파이 배열

In [2]:
np.zeros(shape = (2,2), dtype = np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

### empty() : 활용 가능한 메모리 공간 확보하여 반환

In [3]:
np.empty(shape = (2,4), dtype = np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

#### 생성 시점에서 dtype을 지정해주면 해당 데이터 타입으로 배열 생성