# 03_Numpy_arange

#### range 함수와 동일하게 시작 값 ~ 마지막 값까지 차례대로 생성
#### 형식 (시작 인덱스, 마지막 인덱스, 증가값)
#### 소수점 값, 실수형, 음수값 모두 가능

In [4]:
import numpy as np

np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [7]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])