In [1]:
import numpy as np

test_list = [[1,4,5,8],[1,4,5,122]] #파이썬 기본 배열
npArr = np.array(test_list)
print(npArr)

[[  1   4   5   8]
 [  1   4   5 122]]


In [2]:
print(type(test_list))
print(type(test_list[1][3]))

print(type(npArr[0]))
print(type(npArr[1][3]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [3]:
test_array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(test_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print(test_array.dtype)

# 몇차원이다
print(test_array.ndim)

# 모양 : 데이터 구조 : 3개의 그룹으로 되어있는데 각 그룹에 3개의 데이터가 있다.
print(test_array.shape)

# 그룹의 크기
print(test_array.strides)

int64
2
(3, 3)
(24, 8)


In [5]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [6]:
x.reshape(-1,) # 호출만 한 것 이므로 완전히 변한 것이 아님

array([1, 2, 5, 8, 1, 2, 5, 8])

In [7]:
x = x.reshape(-1,) # 이렇게 할당 해줘야 완전히 바뀌게 됨
x

array([1, 2, 5, 8, 1, 2, 5, 8])

In [8]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
# 둘 다 같은 코드임
# x = np.array(range(8)).reshape(2,2,2)

x = range(8) # 0~7 총 8개의 원소를 가지는 백터 생성
x = np.array(x) # 1차배열
x = x.reshape(2,2,2) # 3차배열로 재정렬
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# x = 을 하지않으면 단지 호출할때만 적용되는 것이기 때문에
# x에 값을 바꿀려면 x = 을 해야한다.

x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])